### ISSUE TITLE
Documentation incorrect

### ISSUE THREAD

**Issue by raulferras** [jeremeamia/xstatic#2]
There is a little error in documentation regarding the implementation of StaticProxies:

```
class Pdo extends StaticProxy
    {
        public function getInstanceIdentifier()
        {
            return 'db';
        }
    }
```

Should be:

```
class Pdo extends StaticProxy
    {
        public static function getInstanceIdentifier()
        {
            return 'db';
        }
    }
```

**Comment by jeremeamia** [comment]
Good catch. Same with the Twig one underneath. Do you want to submit a PR? It's an easy change for me to make, of course, but I'm just wondering if you want the geek cred. :sunglasses:

**Comment by raulferras** [comment]
Haha, sure why not
