### ISSUE TITLE
How to access the container itself?

### ISSUE THREAD

**Issue by ikhsan017** [jeremeamia/xstatic#4]
Hi @jeremeamia 

I have a Silex app, and use xstatic to provide static proxy. I am able to access registered service such as db, twig, etc using the static proxy

```php
class View extends StaticProxy
{
    public static function getInstanceIdentifier()
    {
        return 'twig';
    }
}
```

My question is, how to proxy the container itself? using laravel facade, I can do something like this
```php
class App extends Facade
{
    protected static function getFacadeAccessor()
    {
        return self::$app;
    }

    public static function make($key)
    {
        return self::$app[$key];
    }
}
```
and still able to call all Silex method like ```App::register(new ServiceProvider())```. I can also able to call ```App::make('some_service')``` to access static method of the static proxy class.

Regards,
Ikhsan

**Comment by jeremeamia** [comment]
You should be able to do exactly the same thing. You just need to use the equivalent components of the `StaticProxy`.

```php
class App extends StaticProxy
{
    public static function getInstanceIdentifier()
    {
        return 'app';
    }

    public function getInstance()
    {
        return static::$container;
    }
}
```

_Note: I didn't actually try this, so please report back with your results._

**Comment by ikhsan017** [comment]
Thanks, that works
